version: '3.3'

services:
  web:
    image: nginx:${NGINX_VERSION}
    container_name: ${NGINX_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${APP_DIR}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ${DOCKER_ETC}
      dockerfile: ${DOCKER_PHP}
    image: php-mongo
    container_name: php
    volumes:
      - ${APP_DIR}:/var/www/html
  db:
    image: mongo:${MONGO_VERSION}
    container_name: ${MONGO_NAME}
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ${MONGO_DATA}:/data/db
  console:
    build:
      context: ${DOCKER_ETC}
      dockerfile: ${DOCKER_CONSOLE}
      args:
        APP_USER: ${APP_USER}
    image: console
    container_name: console
    volumes:
      - ${APP_DIR}:/code
    user: ${APP_USER}
    stdin_open: true
    tty: true
