version: '3.3'

services:
  web:
    image: nginx:${NGINX_VERSION}
    container_name: ${NGINX_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${APP_DIR}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: ${APP_ETC}
      dockerfile: Dockerfile.php-fpm
    image: php-mongo
    container_name: php
    volumes:
      - ${APP_DIR}:/var/www/html
  db:
    image: mongo:latest
    container_name: db
#    environment:
#      - MONGO_DATA_DIR=/data/db
#      - MONGO_LOG_DIR=/dev/null
#    volumes:
#      - ./data:/data/db
#    ports:
#      - 27017:27017
#    command: mongod --smallfiles --logpath=/dev/null # --quiet
